name: Docker image Build Process

on:
  workflow_dispatch:
  workflow_call:

jobs:
  docker:
    env:
     appName: "springboot-image"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
